### ISSUE TITLE
Improve discount’s product selection UI

### ISSUE THREAD

**Issue by DidoMarchet** [FosterCommerce/snipcart-craft-plugin#25]
Hi,
I've got a question about discounts.

In the control panel we link products and discounts manually, adding ids in the same way as Snipcart dashboard.

<img width="659" alt="Screenshot 2020-10-15 at 16 07 23" src="https://user-images.githubusercontent.com/38940340/96140764-92aa8f00-0f00-11eb-886b-1ac27b80d9b4.png">

Do you know if there's a smart way to match products and discounts? Or if we can modify the template field?
The goal is something like craft commerce select field

<img width="543" alt="Screenshot 2020-10-15 at 16 11 00" src="https://user-images.githubusercontent.com/38940340/96141306-29774b80-0f01-11eb-8171-50254f04981d.png">
  

Thanks in advance and kind regards,

Davide

**Comment by mattstein** [comment]
This is a nice idea @DidoMarchet, thank you. I think the ability to manually input the product ID would still be important since products could be defined in Craft _outside_ the product details field and not yet known to Snipcart—but offering the ability to choose known products would be much more convenient.
