### ISSUE TITLE
Support for Snipcart 3.0

### ISSUE THREAD

**Issue by goellner** [FosterCommerce/snipcart-craft-plugin#27]
I just saw, that the plugin loads version 2 of Snipcart. Are there plans to support the newer version? The cart looks nicer and the side modal is also better for UX.

**Comment by mattstein** [comment]
Hi @goellner, I’m aware of v3 and waiting for subscription support so the Snipcart plugin upgrade doesn’t lose a feature.

**Comment by zizther** [comment]
Latest update from Snipcart is that recurring payments and subscriptions will be out at the end of March

**Comment by bjerenec** [comment]
Any news on when support for V3 will arrive? It seems that "Subscriptions are currently available in early access with Snipcart's v3 for merchants using Stripe as payment gateway."

**Comment by sjcallender** [comment]
Hi @bjerenec. The changes in the V3 api are significant (I believe it's a complete rewrite). Talking with their team, we've decided to build a new Craft plugin since migrating a Craft implementation, especially the front-end, would be an unwelcome chore for most users of this plugin. We do not have that new plugin work scheduled.

**Comment by croxton** [comment]
Fwiw, it's entirely possible to use Snipcart v3 UI with this plugin if you don't need subscriptions. Just link to the CSS and JS for v3 manually.
