### ISSUE TITLE
Product details field data is cleared when saving an entry to a non-default site

### ISSUE THREAD

**Issue by mikegraham00** [FosterCommerce/snipcart-craft-plugin#31]
I can save a product to the default site, but when I try to save a product in any other sites I get a "Sku cannot be blank" error message.

Does this plugin work with a multi-site setup?

**Comment by johnnynotsolucky** [comment]
Thank you for reporting this @mikegraham00. 

The Snipcart Product Details field was losing its data when an entry was saved to a non-default site - Instead of the site the element was saved on, we were attempting to fetch the record on the current site, which defaults to the primary site. 

This is resolved now in 1.5.2.

**Comment by mikegraham00** [comment]
This is working great now. Thanks for the quick fix.
