### ISSUE TITLE
issue running migration to v2.0

### ISSUE THREAD

**Issue by tobystokes** [FosterCommerce/snipcart-craft-plugin#53]
using the plugin after `composer require "fostercommerce/craft-snipcart:dev-craft4"` all fine, 
but after running `craft update all` :

```
*** applying m230907_112944_migrate_field_to_multicolumn_content
Exception: {"charLimit":["Field Limit is too big for your chosen Column Type."]} (/var/www/html/vendor/fostercommerce/craft-snipcart/src/migrations/m230907_112944_migrate_field_to_multicolumn_content.php:40)
#0 /var/www/html/vendor/fostercommerce/craft-snipcart/src/migrations/m230907_112944_migrate_field_to_multicolumn_content.php(47): fostercommerce\snipcart\migrations\m230907_112944_migrate_field_to_multicolumn_content->resaveFields()
```

(I'm not actually using the plugin's fieldType...)

**Comment by johnnynotsolucky** [comment]
Resolved with a2df4223abaf0fcdd240bf556f8f4f711caf7c9c

> I'm not actually using the plugin's fieldType...

@tobystokes The migration that is being run resaves _all_ fields so that any instances of the plugins field can be resaved correctly within its context.

With this update, I disabled running validation so that nothing should break. If you want to see which fields are not passing validation, you can remove the `false` from [this line](https://github.com/FosterCommerce/snipcart-craft-plugin/commit/a2df4223abaf0fcdd240bf556f8f4f711caf7c9c#diff-e318496a5da78a1ee8130ca8bb0e3f7e29ceef82ea35512dd08954165f03697dR39). I've updated the exception to include the actual field handle and type for clarification.
